server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://your-loki-server:3100/loki/api/v1/push

scrape_configs:
- job_name: api-requests
  static_configs:
  - targets:
      - localhost
    labels:
      job: api-requests
      __path__: /var/log/myapi/*log
