name: React CI/CD to S3

on:
  push: # master Branch에서 front/limited-edition-market 경로에 push 이벤트가 일어났을 때만 실행
    paths:
      - 'front/limited-edition-market/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # 체크아웃
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd front/limited-edition-market
          yarn install

      - name: Build
        run: |
          cd front/limited-edition-market
          yarn build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_CLIENT_KEY: ${{ secrets.REACT_APP_CLIENT_KEY }}
          REACT_APP_CUSTOMER_KEY: ${{ secrets.REACT_APP_CUSTOMER_KEY }}

      - name: Configure AWS credentials # S3 배포
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync with S3
        run: aws s3 sync front/build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
